### ISSUE TITLE
Password for all folder

### ISSUE THREAD

**Issue by churongcon** [kulokenci/goindex-drive#10]
Hello
Password only work on root folder, people can access no need password on 

https://demo.workers.dev/a/b/c

**Comment by kulokenci** [comment]
ya, in version 2.4 I changed it to basic authentication.

**Comment by churongcon** [comment]
Hello, can you add CORS to every file and add PDF viewer for site

**Comment by aiknayan** [comment]
> ya, in version 2.4 I changed it to basic authentication.

This is such a bad discussion. Then There is no uses of password

**Comment by tbowen4** [comment]
i found a workaround i guess,

make a ".password" file in the folder that you want to be protected and in that file put your desired password for that folder that you want to protect

The password file can only protect the file from being listed, and cannot protect the subfolders of the folder from being listed.
It also does not protect the files in the folder from being downloaded.

i found out bout this stuff in https://index.gd.workers.dev/
