### ISSUE TITLE
Drive order mixed up 

### ISSUE THREAD

**Issue by TharinduX** [kulokenci/goindex-drive#37]
When I use numbers in front of the folder names, it's showing like this. [Imgur](https://i.imgur.com/oGqfkLs.png)
I think its only sort with 1-9 numbers only. When it comes to 2 digits. its all mixed up. 
Anyone can help me to fix this? Thanks

**Comment by KickAdnan** [comment]
try rename the 1. to 01., 2. to 02. etc

**Comment by TharinduX** [comment]
> try rename the 1. to 01., 2. to 02. etc

Thanks, It's worked :)
